### ISSUE TITLE
Capital Ө

### ISSUE THREAD

**Issue by talgautb** [JulietaUla/Montserrat#105]
Hi, we have small bug with capital letter "Ө"

example in kazakh language

<img width="380" alt="image" src="https://user-images.githubusercontent.com/1547797/83113773-e94a3480-a0e9-11ea-906c-960385c7da62.png">

**Comment by solmatas** [comment]
Hi,

Thanks for reporting this bug, but capital letter "Ө" is okay in the source file in this repository .

The issue should be open in this repository:
https://github.com/TypeNetwork/Montserrat/commits/master
Which is the new Variable Font version that is now at Google Fonts.

**Comment by solmatas** [comment]
Sorry, what is really happening is that there is an old version in Google Fonts and not the fixed one. The issue with this topic was closed because it was solved in the original sources and the fonts in the repo, but we didn't make a release for it. The new updated version is now in https://github.com/JulietaUla/Montserrat/releases/tag/v7.210
@googlefonts Can we make a PR of the last version? 
cc  @pichotta @davelab6

**Comment by talgautb** [comment]
@solmatas @googlefonts is there any updates?

**Comment by pichotta** [comment]
@talgautb 

The most current font data scheduled to be pushed is here. It has a weight axis variable font and the TTFs which include the fix.
https://github.com/TypeNetwork/Montserrat/tree/master/fonts
