### ISSUE TITLE
Greek support?

### ISSUE THREAD

**Issue by cssobral2013** [JulietaUla/Montserrat#111]

**Comment by alerque** [comment]
cf. #110

**Comment by dangermendez** [comment]
Hi, and thank you for the work you have made designing this font! In response to multiple requests, I have designed a version of Montserrat with Greek support (including Greek Extended (the polytonic glyphs used in Ancient Greek). **Be careful, only regular weight is included**. I have also modified the "π" to look better. 
*NOTE: The polytonic accents look somewhat out of shape because the accented letters were generated using FontForge’s “Build Accented Glyph” feature that put some accents WAY out of place, therefore quick manual adjustments were made.

Here is the zip file, containing the .sfd and the .ttf:
[MontserratEdited.zip](https://github.com/JulietaUla/Montserrat/files/6926586/MontserratEdited.zip)

Below are some sample images:
Image 1: Main Glyphs
Image 2: Greek Wikipedia article about Greek language
Image 3: Lord's Prayer in Ancient Greek

<img width="1269" alt="Screen Shot 2021-08-03 at 3 18 47 PM" src="https://user-images.githubusercontent.com/88398714/128073799-7fd928a8-e01b-40c0-8d0c-0e431b55db3c.png">
<img width="1269" alt="Screen Shot 2021-08-03 at 3 19 00 PM" src="https://user-images.githubusercontent.com/88398714/128073805-08088bb3-26fb-4134-ad21-a541c5473944.png">
<img width="1269" alt="Screen Shot 2021-08-03 at 3 19 09 PM" src="https://user-images.githubusercontent.com/88398714/128073808-88b55e29-2039-4529-b3b2-9ec10fef5377.png">



P.S. I hope the font's creators see this, including @cssobral2013 (who designed Argentum Sans, which is a fork of Montserrat.)! Let me know about this design, review it and feel free to improve it if needed (there are kerning issues with some characters)! Thanks!

**Comment by dangermendez** [comment]
I have published the files in a new repository. Check it out! 
https://github.com/dangermendez/MontserratGreek

I also modified some glyphs to improve accuracy.

**Comment by dangermendez** [comment]
I’m still waiting for a comment from @JulietaUla, and I’m also waiting for collaborators for my project mentioned in my previous comment. Thanks!

**Comment by AndreasZorpidis** [comment]
Posting this here too since it might be helpful to some of you.

I needed a couple more weights (especially a variable version based on the latest v8.000 from Google Fonts) so I decided to give it a try and remix it using glyphs from the font itself. You can find it [here](https://github.com/AndreasZorpidis/Montserrat-Z-Remix).

Notice: I also modified the letters "π" in Greek and "a" in Latin.

Hope that helps :)
