### ISSUE TITLE
The number 1 in montserrat font looks different.

### ISSUE THREAD

**Issue by nahyonii** [JulietaUla/Montserrat#139]
Hello,
The montserrat font style I was expecting is the image below.
![image](https://github.com/JulietaUla/Montserrat/assets/95596990/db72feb8-1547-4b08-8551-a2790275d3f4)
But when I use the montserrat google web font on my web page, the number `1` looks different.
![image](https://github.com/JulietaUla/Montserrat/assets/95596990/86d7152b-5e84-4413-87ee-19e388505e53)

How can I make the font look like the first image?

**Comment by juandelperal** [comment]
Hi @nahyonii 
That's because the upper version uses proportional figures, while the below version is set in tabular figures (look how the width of the characters is always the same).

<img width="553" alt="Screenshot 2023-05-16 at 14 31 09" src="https://github.com/JulietaUla/Montserrat/assets/2414972/83141516-b34d-441c-892f-2adf029b899e">

Are you trying to use that version on the web or using which software?

**Comment by kenmcd** [comment]
> How can I make the font look like the first image?

By hosting the web fonts yourself.
For the fonts in this repository, the default figures are proportional lining.
Google web fonts default figures are always tabular lining (almost).
And there is no way to change that with CSS, etc. because Google web fonts have a limited set of OpenType features which does not include figures.

So the only way for you to have proportional lining figures is for you to host the web fonts from this repository yourself.
