### ISSUE TITLE
Latvian kcommaaccent (ķ) should have a comma below instead of cedilla

### ISSUE THREAD

**Issue by moyogo** [JulietaUla/Montserrat#3]
ķ is part of the set of Latvian letters ĶĻŅŖķļņŗ which are traditionally expected to have the preferred comma-shaped cedilla. Right now it’s the only one in the set with a classic cedilla while ĶĻŅŖļņŗ have the preferred shape.
![screen shot 2015-09-25 at 23 55 53](https://cloud.githubusercontent.com/assets/1923747/10113879/387a2632-63e1-11e5-9455-fbfa72e7760a.png)

**Comment by juandelperal** [comment]
Hi Denis.
Thank you for pointing this issue: I will add this character.
Also, the anchors differences are compatibility problems since Glyphs 2 and
this is originally a Glyphs 1 project. That's why there are some
inconsistencies. We will review the compatibility in all the character set.
Thanks for your feedback.
Best,

j.

**Comment by juandelperal** [comment]
Closed by commit 26a37c2, Thanks!
