### ISSUE TITLE
h and fl.ss01 have incompatible masters in .glyphs files

### ISSUE THREAD

**Issue by moyogo** [JulietaUla/Montserrat#4]
* h in Regular master is missing a topright anchor.
* fl.ss01in Bold master has top, topright and bottom anchors which are not in the other two masters.

**Comment by JulietaUla** [comment]
Hi Denis.
Sorry my delay in the answer!

Thank you for pointing this issue: I will add this character.
Also, the anchors differences are compatibility problems since Glyphs 2 and
this is originally a Glyphs 1 project. That's why there are some
inconsistencies. We will review the compatibility in all the character set.
Thanks for your feedback.
Best,

j.


2015-09-25 20:05 GMT-03:00 Denis Moyogo Jacquerye <notifications@github.com>
:
