### ISSUE TITLE
Add v1 release

### ISSUE THREAD

**Issue by m4rc1e** [JulietaUla/Montserrat#40]
We should add the previous v1.6xxx as a release. We can point people to this for future complaints.

cc @davelab6

**Comment by juandelperal** [comment]
And this?
https://github.com/JulietaUla/Montserrat/tree/v2.001

**Comment by m4rc1e** [comment]
Would be preferable if it was an exact replication of the previous Montserrat fonts hosted on fonts.google.com. They were v1.6 if I remember correctly.

**Comment by tempusrname** [comment]
If I understand correctly; the previous version will be back on google webfonts alongside the new version? This would be a good solution because the new version changed drastically and people like myself want the '400' font weight of the previous version, because its not in the new one.

**Comment by m4rc1e** [comment]
@tempusrname My suggestion is based on creating a tagged release of the previous font so people can self host it. 
![screen shot 2017-02-11 at 21 13 28](https://cloud.githubusercontent.com/assets/7525512/22857545/0fb25822-f09f-11e6-952d-79750c1d9f80.png)

I always make sure I host my own dependencies. We sometimes have to go one step backwards to go two steps forward. The weight had to change to accommodate a vaster range etc.

**Comment by JulietaUla** [comment]
Thank you!

2017-02-11 18:15 GMT-03:00 Marc Foley <notifications@github.com>:

**Comment by tempusrname** [comment]
I think it would feel like an inconvenience for many. Part of my project requires fonts to be linked from google webfonts. Also users would miss out on the benefits such as cache, simplicity and efficiency. with 3,660,889 websites using Montserrat, I'm sure the reason many chose it was because of the '400' or '700' font-weight in the previous version, which is pretty much missing in the new one. I think a good solution might be to bring back the previous version to google webfonts and keep the new version separate for those who prefer it.

Thank you.

**Comment by m4rc1e** [comment]
@tempusrname and what do we say to the people who were begging us for the new weights for years, https://github.com/google/fonts/issues/86?

**Comment by tempusrname** [comment]
They would still be able to use it. Keeping both the old and new Montserrat would be a good solution for everybody and an easy one for you.

**Comment by davelab6** [comment]
Having a duplicate family like "Montserrat Legacy" will complicate the
overall user experience. However with the upcoming OpenType 1.8 Variable
Fonts you'll be able to pick any weight you want :)

On Feb 11, 2017 7:56 PM, "tempusrname" <notifications@github.com> wrote:

They would still be able to use it. Keeping both the old and new Montserrat
would be a good solution for everybody and an easy one for you.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/JulietaUla/Montserrat/issues/40#issuecomment-279187899>,
or mute the thread

**Comment by tempusrname** [comment]
Another solution would be to add the 'normal' font weight of the previous version into the new one.

**Comment by davelab6** [comment]
That won't happen because the initial weight was too heavy for text

**Comment by rgrundig** [comment]
I'm all for new weights, but what's the problem in keeping the old weights as well?

**Comment by davelab6** [comment]
Where will Google fonts keep them?

**Comment by rgrundig** [comment]
I didn't mean having 2 separate families. What I meant is only adding the new weights, not adding new weights + substituting the old ones. Anyway, the point is the new substituted weights are drastically different from the old ones, especially on the shoulders and I get it it was a fresh take on the entire Typeface, but it obviously affects those who use it. Hence, I would rather keep and expand the old version style rather than changing and expanding it.

> Where will Google fonts keep them?

**Comment by juandelperal** [comment]
Here is the old version of the font. This version is what Google Fonts had before the update. You can get woffs too.
https://github.com/JulietaUla/Montserrat/releases/tag/v1.0

**Comment by m4rc1e** [comment]
@juandelperal thanks man!

**Comment by davelab6** [comment]
> I didn't mean having 2 separate families. What I meant is only adding the new weights, not adding new weights + substituting the old ones. 

That won't work, because the weights in a full set of 9 have to grow along a certain kind of curve to be useful as a set. 

See http://www.impallari.com/familysteps/ and http://www.lucasfonts.com/about/interpolation-theory/ and https://www.typotheque.com/articles/type_families

> Anyway, the point is the new substituted weights are drastically different from the old ones, especially on the shoulders and I get it it was a fresh take on the entire Typeface, but it obviously affects those who use it. Hence, I would rather keep and expand the old version style rather than changing so drastically and expanding it.

You're free to do so :)

> Edit: In the new "%" character, the "0's" in it are so big it's really confusing next to a number (which it always is).

I agree, I filed #41 about this :)

**Comment by rgrundig** [comment]
@davelab6 thank you for the links! PS: I love montserrat! <3

**Comment by DanielMcPhee** [comment]
I may be off the mark here -- but even if we self-host the legacy version, if the user (or ourselves for that matter) has the newer version of Montserrat installed locally, won't that mean they'll see their local version instead of the hosted version anyway? In which case they'd see the different version of the 400 weight. (perhaps renaming the file/reference of the self-hosted version will get around this...)

Had been hoping for an update with the full set of weights for a while now so it is much appreciated, but it's had the unfortunate side-effect of breaking the way several of my projects display (me and 3mil+ others by the sounds of it).

**Comment by davelab6** [comment]
@tempusrname @rgrundig 

BTW, somebody wrote to @JulietaUla privated asking why the font looks different, and then as she drafted an answer (with why and the old font link) the person wrote again, 

> I changed my mind. The font does seem to look and perform better. 
>
> I also found that my design looks better with a thinner font rather than a thicker one.
>
> Thank you.

I was pleased to see this :)

**Comment by davelab6** [comment]
@DanielMcPhee 

> I may be off the mark here -- but even if we self-host the legacy version, if the user (or ourselves for that matter) has the newer version of Montserrat installed locally, won't that mean they'll see their local version instead of the hosted version anyway? 

Yes. 

> In which case they'd see the different version of the 400 weight. (perhaps renaming the file/reference of the self-hosted version will get around this...)

It will, yes. 

> Had been hoping for an update with the full set of weights for a while now so it is much appreciated, but it's had the unfortunate side-effect of breaking the way several of my projects display (me and 3mil+ others by the sounds of it).

I am curious what the breakage was; from my perspective the change is an improvement.

**Comment by DanielMcPhee** [comment]
> I am curious what the breakage was; from my perspective the change is an improvement.

Objectively it is an improvement, particularly for new projects where you know what you're working with.

Subjectively, perhaps not. Personally I used the old 400 weight for a semi-bold look, which several of my projects hinged on visually. So from my perspective, the rug has been pulled out from under those projects aesthetically.

I suspect many others will suffer the same fate -- but not even be aware of it yet since they'll most likely have the old font set installed locally.

**Comment by davelab6** [comment]
> Personally I used the old 400 weight for a semi-bold look, which several of my projects hinged on visually. So from my perspective, the rug has been pulled out from under those projects aesthetically.

But the new 500 or 600 won't work for the same look?

**Comment by DanielMcPhee** [comment]
> But the new 500 or 600 won't work for the same look?

No, unfortunately not. I know this must seem like an odd thing to complain about, but the new weights render quite differently to the original 400. It had a nice rounded, anti-aliased look.

**Comment by davelab6** [comment]
On Feb 20, 2017 3:46 AM, "DanielMcPhee" <notifications@github.com> wrote:

But the new 500 or 600 won't work for the same look?

No, unfortunately not. I know this must seem like an odd thing to complain
about, but the new weights render quite differently to the original 400. It
had a nice rounded, anti-aliased look


Mmm. Maybe a hinting difference.

Which OS/browser was that?

As I recall Montserrat didn't get hand hinted, and perhaps not even
ttfautohinted...

**Comment by juandelperal** [comment]
@DanielMcPhee 
You can use this way to avoid conflict with installed/cached fonts

```css
@font-face {
    font-family: 'Montserrat1.0';
    src:  url('Montserrat-Bold.woff2') format('woff2'),
          url('Montserrat-Bold.woff') format('woff');
}
```

**Comment by DanielMcPhee** [comment]
> Which OS/browser was that?

@davelab6 Chrome on Windows 10. Many fonts look awful in that environment, but Montserrat 400 always look edgreat for small amounts of texts (headlines, UI elements etc.).

**Comment by DanielMcPhee** [comment]
>You can use this way to avoid conflict with installed/cached fonts
@juandelperal - Thanks much! I will look into this one.
