### ISSUE TITLE
why ttf is not in webfonts folder?

### ISSUE THREAD

**Issue by bi-kai** [JulietaUla/Montserrat#50]
why ttf is not in webfonts folder?
does ttf could be used for web pages?
And do you have a .css file for the webfonts?

**Comment by davelab6** [comment]
Yes it can be. It is in a separate folder because it can be installed
locally.

On Aug 13, 2017 7:28 PM, "bikai" <notifications@github.com> wrote:

why ttf is not in webfonts folder?
does ttf could be used for web pages?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JulietaUla/Montserrat/issues/50>, or mute the thread

**Comment by bi-kai** [comment]
@davelab6 do you provide Montserrat webfont? why there is no .css or .scss file in this repo?

**Comment by davelab6** [comment]
Use https://github.com/majodev/google-webfonts-helper

**Comment by davelab6** [comment]
Today TTF files are no longer needed; all browsers in common use accept WOFF files.
