### ISSUE TITLE
Letter "Є" in Ukrainian font slips under the baseline 

### ISSUE THREAD

**Issue by zayceva** [JulietaUla/Montserrat#79]
![image](https://user-images.githubusercontent.com/42452190/44235740-3bd78c80-a1b3-11e8-9cca-90f5a25e02d5.png)

**Comment by lubkooleskiv** [comment]
@zayceva do you find any solution for this?

**Comment by zayceva** [comment]
@lubkooleskiv partially. Avoid using 14 and 16 font-size. 15 is ok

**Comment by solmatas** [comment]
May I ask you in which browser are you checking this?
Because in Firefox and Chrome it works good.

See images below:
Firefox, 14 px
<img width="345" alt="firefox-16" src="https://user-images.githubusercontent.com/8105496/50603172-e679ee80-0eb9-11e9-84a1-703f8ab5ef94.png">

Chrome, 16 px and 14 px
<img width="396" alt="chrome_16" src="https://user-images.githubusercontent.com/8105496/50603281-4c667600-0eba-11e9-9036-255697d26381.png">
<img width="396" alt="chrome_14" src="https://user-images.githubusercontent.com/8105496/50603282-4c667600-0eba-11e9-97ea-4003da624864.png">

**Comment by zayceva** [comment]
Chrome on Windows

**Comment by lubkooleskiv** [comment]
@solmatas hi.
I have problems in Chrome 71.0.3578.98 (OS Windows 10). 

![image](https://user-images.githubusercontent.com/36737913/50638211-98bac000-0f65-11e9-8f28-0a0b34c3e0d1.png)

![image](https://user-images.githubusercontent.com/36737913/50638240-aff9ad80-0f65-11e9-91fc-eb9758b2af28.png)

**Comment by lubkooleskiv** [comment]
@solmatas  @davelab6  @graphicore. 
Do you have any solution for this?

**Comment by AlsoScratch** [comment]
@solmatas I would definitely appreciate some acknowledgement.

**Comment by solmatas** [comment]
Hi! the repo was updated last February and that glyph was modified. But it is not updated in Google Fonts directory. You can download the font files, test it in your browser and we will appreciate your feedback. Thanks!

**Comment by AlsoScratch** [comment]
> Hi! the repo was updated last February and that glyph was modified. But it is not updated in Google Fonts directory. You can download the font files, test it in your browser and we will appreciate your feedback. Thanks!

When should I expect an official release?
