### ISSUE TITLE
The letter uppercase "Ө" (Oe) displaying with a huge gap.

### ISSUE THREAD

**Issue by duuuk** [JulietaUla/Montserrat#87]
Hello! Thank you for your work on the beautiful font. However there is a single issue on its Cyrillic Extended version. 
The uppercase "Ө" has a gap on both ends of its middle dash. (Sorry about mislabeling of the parts). Other than that, perfect!
Thank you!
Dulguun

<img width="569" alt="screen shot 2019-02-18 at 3 43 24 pm" src="https://user-images.githubusercontent.com/6396642/52935538-a355db00-3394-11e9-9c5e-9967580c88b0.png">

**Comment by solmatas** [comment]
Hello Dulguun,

Thank you for giving us notice about this error.
I uploaded in Github the exported files (ttf, otf and webfonts) again, because the path direction of those letters were okay in the source files. 
May be @davelab6 <https://github.com/davelab6> can push this in fonts.google.com.

Cheers,
Sol

**Comment by duuuk** [comment]
@solmatas @davelab6 

Thank you! Hope to see it soon on google fonts! 

Cheers!
Dulguun

**Comment by duuuk** [comment]
Hello @solmatas & @davelab6 !

I see that the issue is not yet resolved on Google Fonts. I know you guys are busy but can I get an estimate date on the update? I really want to use the font on my product. 

Thank you!
Dulguun
