### ISSUE TITLE
Lowercase eth

### ISSUE THREAD

**Issue by stefanvaldimarsson** [JulietaUla/Montserrat#97]
The shape of the lowercase eth (Icelandic letter) is not very good. The basic principle is that the bottom half of the glyph should be the same shape and size as the lowercase o. In Montserrat the bottom half of the lowercase eth is far too small. Another problem is that the ascender should start from the top and not from the left hand side as it does in Montserrat. There principles are discussed here: https://sites.google.com/view/briem/design starting from about midway through the page.

**Comment by juandelperal** [comment]
Thanks @stefanvaldimarsson 
We love this kind of feedback, it is very useful for non native speakers :)

Since the ascenders are pretty short we don't have the chance to make the counter similar to the o. The eth was redesigned in the last update but we can rollback the change if needed

Actual version:
<img width="765" alt="Screen Shot 2019-11-26 at 10 56 34" src="https://user-images.githubusercontent.com/2414972/69639631-a1176000-103b-11ea-91a4-d02c1de34689.png">

Previews version:
<img width="801" alt="Screen Shot 2019-11-26 at 10 57 26" src="https://user-images.githubusercontent.com/2414972/69639639-a5437d80-103b-11ea-8c44-1c4fa478f4f8.png">

**Comment by stefanvaldimarsson** [comment]
Thanks for looking into this. I think the previous version looks much more reasonable. In that version the starting point of the ascender is in a good location. I understand that there is not a lot of space to make the counter larger, maybe the crossbar could be shortened to make more space but it is proably going to be quite delicate.

So for now I like the suggestion of reverting to the previous version.

**Comment by juandelperal** [comment]
Great, thanks

Right now there are contributors working on converting Montserrat into a Variable font, which are great news. When this merged we will work on your suggestion.

**Comment by AlsoScratch** [comment]
Actually there is a slightly more serious issue: the ð character is barely taller than caps height!
<img width="182" alt="Screenshot 2020-05-30 at 9 26 04 PM" src="https://user-images.githubusercontent.com/48752273/83329468-4ac1fd00-a2bc-11ea-8109-f25a9c12333f.png">

**Comment by JulietaUla** [comment]
Thank you for your valuable feedback and understanding throughout this discussion. We've reverted the changes to the lowercase eth, aligning it more closely for the starting point of the ascender.
